=== H-hao/excel-engine/src/main/java/com/hh/excel/engine/config/excelMapper.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!-- 可以配置一些全局函数（放在根节点下） -->
<!ELEMENT excelMappers (font* | style* | headerOfPage* | footerOfPage* | excelMap* | excelImport* | excelExport* )+>

<!ELEMENT excelExport (header | datas | map | propertiesForTemplate)>
<!ATTLIST excelExport
	id ID #REQUIRED
	excelMapRef CDATA #IMPLIED
	templateLocation CDATA #IMPLIED
	fileName CDATA #IMPLIED
	exportType CDATA #IMPLIED
	title CDATA #IMPLIED
	freezeTop CDATA #IMPLIED
	freezeLeft CDATA #IMPLIED
	startRowNo CDATA #IMPLIED
	startCellNo CDATA #IMPLIED
	styleRef CDATA #IMPLIED
	headerStyleRef CDATA #IMPLIED
	maxColumnWidth CDATA #IMPLIED
	maxRowHeight CDATA #IMPLIED
	headerOfPageRef CDATA #IMPLIED
	footerOfPageRef CDATA #IMPLIED
	isIndexWay CDATA #IMPLIED
	startIndexForTemplate CDATA #IMPLIED
	isConsecutive CDATA #IMPLIED
	ignoreColumnIndex CDATA #IMPLIED
	rowFailThreshold CDATA #IMPLIED
	columnFailThreshold CDATA #IMPLIED
>

<!ELEMENT excelImport (map | propertiesForTemplate)>
<!ATTLIST excelImport
	id ID #REQUIRED
	type CDATA #IMPLIED
	excelMapRef CDATA #IMPLIED
	templateLocation CDATA #IMPLIED
	startRowNo CDATA #IMPLIED
	startCellNo CDATA #IMPLIED
	isIndexWay CDATA #IMPLIED
	startIndexForTemplate CDATA #IMPLIED
	isConsecutive CDATA #IMPLIED
	ignoreColumnIndex CDATA #IMPLIED
	rowFailThreshold CDATA #IMPLIED
	columnFailThreshold CDATA #IMPLIED
>

<!ELEMENT excelMap (mapping*)>
<!ATTLIST excelMap
	id ID #REQUIRED
	type CDATA #REQUIRED
>

<!ELEMENT mapping EMPTY>
<!ATTLIST mapping
	property CDATA #REQUIRED
	effectiveHeader CDATA #REQUIRED
	<!-- 有效的索引，与 header 同样的作用 -->
	effectiveIndex CDATA #IMPLIED
>

<!ELEMENT headerOfPage (property*)>
<!ATTLIST headerOfPage
	id ID #REQUIRED
>
<!ELEMENT footerOfPage (property*)>
<!ATTLIST footerOfPage
	id ID #REQUIRED
>

<!ELEMENT font (property*)>
<!ATTLIST font
	id ID #REQUIRED
	extend CDATA #IMPLIED
>

<!ELEMENT style (property*)>
<!ATTLIST style
	id ID #REQUIRED
	extend CDATA #IMPLIED
>

<!ELEMENT header (list? | value?)*>
<!ATTLIST header
	styleRef CDATA #IMPLIED
>

<!ELEMENT datas (list? | value?)*>
<!ATTLIST datas
	styleref CDATA #IMPLIED
>

<!ELEMENT list (value*)>
<!ATTLIST list
>

<!ELEMENT map (entry*)>
<!ATTLIST map
>

<!ELEMENT entry (#PCDATA | setter | getter)*>
<!ATTLIST entry
	required CDATA #IMPLIED
	header CDATA #IMPLIED
	columnIndex CDATA #IMPLIED
	getter CDATA #IMPLIED
	setter CDATA #IMPLIED
	copyTo CDATA #IMPLIED
	cellType CDATA #IMPLIED
	width CDATA #IMPLIED
	maxWidth CDATA #IMPLIED
	blank CDATA #IMPLIED
	pattern CDATA #IMPLIED
	dataFormat CDATA #IMPLIED
	dataSource CDATA #IMPLIED
	selectSql CDATA #IMPLIED
>

<!ELEMENT propertiesForTemplate (entry) >
<!ATTLIST propertiesForTemplate

>
<!ELEMENT setter (#PCDATA | if)*>
<!ATTLIST setter
>

<!ELEMENT getter (#PCDATA | if)*>
<!ATTLIST getter
>

<!ELEMENT value (#PCDATA | if)*>
<!ATTLIST value
>

<!ELEMENT if (#PCDATA)>
<!ATTLIST if
	test CDATA #REQUIRED
>
<!ELEMENT property (#PCDATA)>
<!ATTLIST property
	name CDATA #REQUIRED
	value CDATA #IMPLIED
	ref CDATA #IMPLIED
>

=== H-hao/excel-engine/src/main/java/com/hh/excel/engine/config/excelMapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE excelMappers SYSTEM "/com/hh/excel/engine/config/excelMapper.dtd">
<excelMappers>
	<!--内部默认的一些配置，读取这些配置并保存-->
	<!--
		还是直接通过构造方法（或 get 方法）来获取默认配置
		构造方法：不可取，每次都 new
		get 方法：只会创建一次
		TODO 使用 默认配置 还是 默认 get 方法？
		默认配置：解析为 Vo 对象，再转换为 poi 的对象
		get：获取 Vo 对象，在转换为 poi 对象
		配置比 get 方法多了个解析过程，还是使用 get 方法较好
	-->

	<!-- 默认表头样式 -->
	<style id="defaultHeaderStyle">
		<property name="font" ref="defaultBoldFont"/>
		<property name="wrapText" value="true"/>
		<property name="alignment" value="center"/>
		<property name="verticalAlignment" value="center"/>
	</style>

	<!-- 默认样式 -->
	<style id="defaultCellStyle">
		<property name="font" ref="defaultFont"/>
		<property name="wrapText" value="false"/>
		<property name="alignment" value="center"/>
		<property name="verticalAlignment" value="center"/>
	</style>

	<!-- 默认字体 -->
	<font id="defaultFont">
		<property name="fontName" value="微软雅黑"/>
		<property name="bold" value="false"/>
		<property name="fontHeightInPoints" value="10"/>
	</font>

	<!-- 默认加粗字体 -->
	<font id="defaultBoldFont">
		<property name="fontName" value="微软雅黑"/>
		<property name="bold" value="true"/>
		<property name="fontHeightInPoints" value="12"/>
	</font>
</excelMappers>
